name: Pull / SNMP2MQTT

on:
  pull_request:
    types: [opened, edited]
  workflow_call:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  test:
    name: Test / Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm/v8
          - linux/arm64
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          platforms: ${{ matrix.platform }}
          labels: |
            maintainer=andrewjswan
            org.opencontainers.image.title=snmp2mqtt
            org.opencontainers.image.description=Expose SNMP sensors to MQTT
          tags: ${{env.REGISTRY_IMAGE}}:test
